/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: urbanmasque (https://sketchfab.com/urbanmasque)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boxing-heavy-bag-576b851a49f24693bf37e09a944b0f99
Title: Boxing Heavy Bag
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const BoxingBag =(props)=> {
  const { nodes, materials } = useGLTF('/models/boxingBag.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[40.927, -74.829, 33.911]} rotation={[-Math.PI, 1.571, 0]} scale={0.034}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/boxingBag.glb')
export default BoxingBag