/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: giga (https://sketchfab.com/gits3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iron-dumbel-f5ccda1a705a4f68a360060bb69219c2
Title: iron Dumbel
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
const Dumbbell2 = (props) => {
  const { nodes, materials } = useGLTF('/models/dumbbell2.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[0, 47.992, 0]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[7.751, 7.751, 100]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grappler_Grappler_0.geometry}
            material={materials.Grappler}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grappler_Weight_0.geometry}
            material={materials.Weight}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/dumbbell2.glb')
export default Dumbbell2