/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AdiXXioN (https://sketchfab.com/adixxion)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/russian-dumbbell-red-903e292f8ddb4db88cd7bd75c707d95b
Title: Russian Dumbbell Red
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Dumbbell1 = (props) =>  {
  const { nodes, materials } = useGLTF('/models/dumbbell1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Pesa_rusa}
        position={[-0.001, 0.612, -0.005]}
        rotation={[0, 0.381, 0]}
        scale={3.732}
      />
    </group>
  )
}

useGLTF.preload('/models/dumbbell1.glb')
export default Dumbbell1