/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: neutralize (https://sketchfab.com/neutralize)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gym-d8da8a2e7a6144ea851a76e37e98eea7
Title: Gym
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Gym = (props) => {

  const gymRef = useRef()

  useGSAP(() => {

    if (gymRef.current) {
      gsap.to(gymRef.current.position, {
        x: gymRef.current.position.x + 0.4,
        y: gymRef.current.position.y + 0.2,
        duration: 1.5,
        repeat: -1,
        yoyo: true
      });
    }
  }, []); // Ensure the effect runs only once (on mount)
  
  const { nodes, materials } = useGLTF('/models/gym.glb')
  return (
    <group ref={gymRef}
     {...props} dispose={null}>
      <group position={[-4.205, 0, 3.251]} rotation={[-Math.PI / 2, 0, 0]}>
      <meshLambertMaterial color={"gray"}/>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.curler_gymbench_1DUMBELL_0.geometry}
          material={materials.gymbench_1DUMBELL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.curler_gymbench_1METAL_0.geometry}
          material={materials.gymbench_1METAL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.curler_gymbench_1THREAD_0.geometry}
          material={materials.gymbench_1THREAD}
        />
      </group>
      <group position={[-4.205, 0, 3.251]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.benchh_gymbench_2BLAK_0.geometry}
          material={materials.gymbench_2BLAK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.benchh_gymbench_1METAL_0.geometry}
          material={materials.gymbench_1METAL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.benchh_gymbench_1SPONGE2_0.geometry}
          material={materials.gymbench_1SPONGE2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.benchh_gymbench_2CUSH_0.geometry}
          material={materials.gymbench_2CUSH}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.benchh_gymbench_1LILCUSH_0.geometry}
          material={materials.gymbench_1LILCUSH}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.benchh_gymbench_1DUMBELL_0.geometry}
          material={materials.gymbench_1DUMBELL}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/gym.glb')
export default Gym