/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MHKstudio (https://sketchfab.com/mhkstudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spring-collar-f89f299a07154ee5902f4c036c86ccdd
Title: Spring Collar
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const SpringCollar = (props) => {
  const { nodes, materials } = useGLTF('spring_collar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spring_Collar_Spring_Collar_0.geometry}
        material={materials.Spring_Collar}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('spring_collar.glb')
export default SpringCollar