/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gallery4D (https://sketchfab.com/ahmadrezagh671)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smart-watch-low-poly-ea4f25ed03c54c35a5fe3b1218bdc76b
Title: Smart Watch Low Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Watch = (props) => {
  const { nodes, materials } = useGLTF('/models/smart_watch_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.116, -0.082, -0.165]} scale={0.053}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.screen}
            position={[0, 0.003, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.button}
            position={[0.607, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.end_band}
            position={[0, -2.632, -0.897]}
            rotation={[3.013, 0, 0]}
            scale={[0.956, 0.701, 0.986]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.band}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/smart_watch_low_poly.glb')
export default Watch
