/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sam.c.roberts (https://sketchfab.com/sam.c.roberts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arrowsmult-8185abe5c8cf44279c8c53bc1a00e159
Title: Arrowsmult
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Arrow = (props) => {
  const { nodes, materials } = useGLTF('./models/arrow.glb')
  const arrowRef = useRef()

  useGSAP(() => {

    if (arrowRef.current) {
      gsap.to(arrowRef.current.position, {
        x: arrowRef.current.position.x + 0.4,
        y: arrowRef.current.position.y + 0.4,
        duration: 1,
        repeat: -1,
        yoyo: true,
        animations: true

      });
    }
  }, []);

  return (
    <group ref={arrowRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_0.geometry}
          material={materials['Scene_-_Root']}
          position={[0.499, 0.486, 0]}
          rotation={[-1.366, 1.159, 1.967]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/arrow.glb')
export default Arrow