/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: neutralize (https://sketchfab.com/neutralize)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gym4-536508b7fe2f41d4b68ed4762a7fc5f4
Title: Gym4
*/

import React, { useRef } from 'react'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'
import { useGLTF } from '@react-three/drei'

const Dumbbell3 =(props)=> {
  const { nodes, materials } = useGLTF('/models/dumbbell3.glb')
  const dbRef = useRef()

  useGSAP(() => {

    if (dbRef.current) {
      gsap.to(dbRef.current.position, {
        x: dbRef.current.position.x - 0.2,
        y: dbRef.current.position.y - 0.7,
        duration: 1.5,
        repeat: -1,
        yoyo: true
      });
    }
  }, []);

  return (
    <group ref={dbRef} {...props} dispose={null}>
      <group
        position={[-8.592, 6.016, 16.852]}
        rotation={[Math.PI, -1.099, Math.PI]}
        scale={[-0.902, 0.902, 0.902]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arch27_023_01__0.geometry}
          material={materials['Scene_-_Root']}
          position={[8.453, 0.034, 0]}
        />
      </group>
      <group position={[-8.009, 6.016, 15.709]} rotation={[0, -0.472, 0]} scale={[-1, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arch27_023_04__0.geometry}
          material={materials['Scene_-_Root']}
          position={[0, 0, -1.162]}
        />
      </group>
      <group position={[-8.812, 6.016, 17.283]} rotation={[0, -0.472, 0]} scale={[-1, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arch27_023_05__0.geometry}
          material={materials['Scene_-_Root']}
          position={[0, 0, -1.162]}
        />
      </group>
      <group position={[8.592, 6.016, -16.852]} rotation={[Math.PI, -1.099, Math.PI]} scale={0.902}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arch27_023_07__0.geometry}
          material={materials['Scene_-_Root']}
          position={[8.453, 0.034, 0]}
        />
      </group>
      <group position={[8.009, 6.016, -15.709]} rotation={[Math.PI, 0.472, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arch27_023_10__0.geometry}
          material={materials['Scene_-_Root']}
          position={[0, 0, -1.162]}
        />
      </group>
      <group position={[8.812, 6.016, -17.283]} rotation={[Math.PI, 0.472, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arch27_023_11__0.geometry}
          material={materials['Scene_-_Root']}
          position={[0, 0, -1.162]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch27_023_00__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-4.752, 6.05, 9.321]}
        rotation={[Math.PI, -1.099, Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch27_023_02__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-10.13, 6.016, 19.869]}
        rotation={[Math.PI, 0.472, -0.698]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch27_023_03__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-7.395, 6.016, 14.505]}
        rotation={[0, -0.472, 0]}
        scale={[-2.029, 2.029, 1.529]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch27_023_06__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-4.752, 6.05, 9.321]}
        rotation={[Math.PI, -1.099, Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch27_023_08__0.geometry}
        material={materials['Scene_-_Root']}
        position={[10.13, 6.016, -19.869]}
        rotation={[0, -0.472, -2.443]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch27_023_09__0.geometry}
        material={materials['Scene_-_Root']}
        position={[7.395, 6.016, -14.505]}
        rotation={[Math.PI, 0.472, Math.PI]}
        scale={[2.029, 2.029, 1.529]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch27_023_12__0.geometry}
        material={materials['Scene_-_Root']}
        position={[4.752, 6.05, -9.321]}
        rotation={[Math.PI, -1.099, Math.PI]}
      />
    </group>
  )
}

useGLTF.preload('/models/dumbbell3.glb')
export default Dumbbell3
