/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: neutralize (https://sketchfab.com/neutralize)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gym2-1c01b23c5ff447a891bea85d273071c0
Title: Gym2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Machine = (props) => {
  const { nodes, materials } = useGLTF('/models/gym2.glb')
  const machineRef = useRef()

  useGSAP(() => {

    if (machineRef.current) {
      gsap.to(machineRef.current.position, {
        x: machineRef.current.position.x + 0.2,
        y: machineRef.current.position.y + 0.4,
        duration: 1.5,
        repeat: -1,
        yoyo: true
      });
    }
  }, []);

  return (
    <group ref={machineRef} {...props} dispose={null}>
      <group position={[0, 799.727, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-76.571, 245.173, -521.8]}
          rotation={[0.006, -0.001, -1.753]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_371__0.geometry}
            material={materials.Arch27_371__0}
            position={[7.957, 0, -18.504]}
          />
        </group>
        <group
          position={[-601.425, -80.337, -772.162]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_372__0.geometry}
            material={materials.Arch27_371__0}
            position={[8.892, 3.235, -202.917]}
          />
        </group>
        <group
          position={[-561.676, 135.81, -767.562]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_373__0.geometry}
            material={materials.Arch27_371__0}
            position={[8.892, -1.011, 0]}
          />
        </group>
        <group
          position={[-529.878, 129.962, -767.562]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_374__0.geometry}
            material={materials.Arch27_371__0}
            position={[-20.961, -1.011, 0]}
          />
        </group>
        <group position={[-561.672, 53.11, -746.386]} rotation={[0, 0, -1.753]} scale={0.781}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_375__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -3.09]}
          />
        </group>
        <group position={[-532.275, 212.971, -746.386]} rotation={[0, 0, -1.753]} scale={0.781}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_376__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -3.09]}
          />
        </group>
        <group
          position={[-521.929, 351.951, -772.162]}
          rotation={[-Math.PI / 2, 0.182, Math.PI]}
          scale={[-1.083, 1.083, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_377__0.geometry}
            material={materials.Arch27_371__0}
            position={[8.892, 3.235, -202.917]}
          />
        </group>
        <group
          position={[-114.792, 53.629, -450.824]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_378__0.geometry}
            material={materials.Arch27_371__0}
            position={[53.547, -19.301, 59.636]}
          />
        </group>
        <group
          position={[-155.863, 61.182, -484.559]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_379__0.geometry}
            material={materials.Arch27_371__0}
            position={[92.105, 11.846, 59.636]}
          />
        </group>
        <group
          position={[80.273, -53.679, -437.066]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_380_MyMtl_01_0.geometry}
            material={materials.MyMtl_01}
            position={[0, 0, -5.376]}
          />
        </group>
        <group
          position={[-201.425, 69.466, 104.569]}
          rotation={[-0.032, -0.167, -0.185]}
          scale={[1.083, 1.083, 0.733]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_381__0.geometry}
            material={materials.Arch27_371__0}
            position={[31.522, 0.267, -386.869]}
          />
        </group>
        <group
          position={[-146.81, 59.492, -81.003]}
          rotation={[-0.032, -0.167, -0.185]}
          scale={[1.083, 1.083, 0.733]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_382__0.geometry}
            material={materials.Arch27_371__0}
            position={[9.962, 0.081, -124.471]}
          />
        </group>
        <group
          position={[-94.221, 49.836, -87.719]}
          rotation={[0.77, 1.313, -0.787]}
          scale={[0.474, 0.474, 0.32]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_383__0.geometry}
            material={materials.Arch27_371__0}
            position={[10.426, 0.08, -124.488]}
          />
        </group>
        <group
          position={[-190.83, 67.813, 320.494]}
          rotation={[-0.042, -0.222, -1.757]}
          scale={0.859}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_384__0.geometry}
            material={materials.Arch27_371__0}
            position={[0.23, 37.256, 32.619]}
          />
        </group>
        <group
          position={[-111.793, 53.073, -93.331]}
          rotation={[0.77, 1.313, -0.787]}
          scale={[0.474, 0.474, 0.32]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_385_MyMtl_01_0.geometry}
            material={materials.MyMtl_01}
            position={[5.672, 0.04, -66.469]}
          />
        </group>
        <group
          position={[-129.654, 56.358, -139.106]}
          rotation={[-0.032, -0.167, -0.185]}
          scale={[1.083, 1.083, 0.733]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_386_MyMtl_01_0.geometry}
            material={materials.MyMtl_01}
            position={[3.159, 0.023, -42.3]}
          />
        </group>
        <group
          position={[211.883, -5.936, -684.139]}
          rotation={[Math.PI / 2, -0.182, -2.726]}
          scale={[-1.083, 1.083, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_387__0.geometry}
            material={materials.Arch27_371__0}
            position={[130.914, -174.337, 60.098]}
          />
        </group>
        <group
          position={[105.643, 84.281, -437.066]}
          rotation={[-Math.PI / 2, 0.182, Math.PI]}
          scale={[-1.083, 1.083, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_388_MyMtl_01_0.geometry}
            material={materials.MyMtl_01}
            position={[0, 0, -5.376]}
          />
        </group>
        <group
          position={[492.953, -58.133, 445.01]}
          rotation={[-0.468, -1.184, -2.07]}
          scale={[-2.089, 2.089, 2.089]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_389__0.geometry}
            material={materials.Arch27_371__0}
            position={[45.78, 75.591, 0]}
          />
        </group>
        <group
          position={[391.137, -39.423, 424.653]}
          rotation={[-1.183, -1.374, -1.19]}
          scale={[0.607, 0.607, 0.41]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_390__0.geometry}
            material={materials.Arch27_371__0}
            position={[10.426, 0.08, -124.488]}
          />
        </group>
        <group
          position={[414.7, -43.748, 425.769]}
          rotation={[-1.183, -1.374, -1.19]}
          scale={[0.607, 0.607, 0.41]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_391__0.geometry}
            material={materials.Arch27_371__0}
            position={[5.672, 0.04, -66.47]}
          />
        </group>
        <group
          position={[530.487, -65.035, 528.671]}
          rotation={[3.102, 0.212, 0.186]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_392__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.742]}
          />
        </group>
        <group
          position={[518.278, -62.785, 491.996]}
          rotation={[0.048, 0.257, -0.188]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_393__0.geometry}
            material={materials.Arch27_371__0}
            position={[-5.48, -0.004, -38.425]}
          />
        </group>
        <group
          position={[471.932, -54.267, 559.307]}
          rotation={[-0.061, -0.319, -1.762]}
          scale={[-2.312, 2.312, 2.312]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Arch27_394_Material_#35_0'].geometry}
            material={materials.Material_35}
            position={[27.492, -9.838, 2.487]}
          />
        </group>
        <group
          position={[393.523, -81.695, 541.633]}
          rotation={[-0.061, -0.319, -2.119]}
          scale={[-0.501, 1.043, 1.043]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_395__0.geometry}
            material={materials.Arch27_371__0}
            position={[27.497, -9.834, 2.849]}
          />
        </group>
        <group
          position={[408.411, -0.739, 541.633]}
          rotation={[-0.061, -0.319, -1.406]}
          scale={[0.501, 1.043, 1.043]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_396__0.geometry}
            material={materials.Arch27_371__0}
            position={[27.496, -9.834, 2.849]}
          />
        </group>
        <group
          position={[542.854, -67.31, 586.787]}
          rotation={[-0.468, -1.184, -2.07]}
          scale={[-2.312, 2.312, 2.312]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_397__0.geometry}
            material={materials.Arch27_371__0}
            position={[45.78, 10.452, 0]}
          />
        </group>
        <group
          position={[458.65, -51.825, 531.416]}
          rotation={[-0.061, -0.319, -1.762]}
          scale={[-2.312, 2.312, 2.312]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_398__0.geometry}
            material={materials.Arch27_371__0}
            position={[27.492, -0.457, 12.062]}
          />
        </group>
        <group
          position={[363.372, -34.304, 125.782]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_399__0.geometry}
            material={materials.Arch27_371__0}
            position={[5.533, -71.559, 0]}
          />
        </group>
        <group
          position={[246.291, -12.773, -284.044]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_400__0.geometry}
            material={materials.Arch27_371__0}
            position={[115.447, 306.838, 0]}
          />
        </group>
        <group
          position={[352.697, -76.125, -119.828]}
          rotation={[1.605, -0.129, 0.004]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_401__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.582]}
          />
        </group>
        <group
          position={[317.926, -39.114, -95.03]}
          rotation={[0.417, -0.996, -1.086]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_402__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.582]}
          />
        </group>
        <group
          position={[278.383, -42.503, -164.822]}
          rotation={[0.81, -0.893, -0.638]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_403__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.582]}
          />
        </group>
        <group
          position={[245.359, -72.871, -278.806]}
          rotation={[1.438, -0.021, -0.003]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_404__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.582]}
          />
        </group>
        <group
          position={[-380.871, 13.003, -607.982]}
          rotation={[Math.PI / 2, -0.154, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_405__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.582]}
          />
        </group>
        <group
          position={[-252.755, -6.927, -590.152]}
          rotation={[Math.PI / 2, -0.154, 0]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_406__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.582]}
          />
        </group>
        <group position={[177.16, -98.532, -378.526]} rotation={[-Math.PI, 0, 0.182]} scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_407__0.geometry}
            material={materials.Arch27_371__0}
            position={[3.806, 21.805, 54.607]}
          />
        </group>
        <group
          position={[352.187, -114.945, -746.386]}
          rotation={[0, 0, 1.389]}
          scale={[-0.781, 0.781, 0.781]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_408__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -3.09]}
          />
        </group>
        <group
          position={[349.813, -31.81, -767.562]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={[-1.083, 1.083, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_409__0.geometry}
            material={materials.Arch27_371__0}
            position={[-20.961, -1.011, 0]}
          />
        </group>
        <group
          position={[381.585, 44.915, -746.386]}
          rotation={[0, 0, 1.389]}
          scale={[-0.781, 0.781, 0.781]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_410__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -3.09]}
          />
        </group>
        <group
          position={[381.612, -37.658, -767.562]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={[-1.083, 1.083, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_411__0.geometry}
            material={materials.Arch27_371__0}
            position={[8.892, -1.011, 0]}
          />
        </group>
        <group
          position={[421.359, 178.484, -772.162]}
          rotation={[-Math.PI / 2, 0.182, -Math.PI]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_412__0.geometry}
            material={materials.Arch27_371__0}
            position={[8.892, 3.235, -202.917]}
          />
        </group>
        <group
          position={[341.863, -253.804, -772.162]}
          rotation={[Math.PI / 2, -0.182, 0]}
          scale={[-1.083, 1.083, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_413__0.geometry}
            material={materials.Arch27_371__0}
            position={[8.892, 3.235, -202.917]}
          />
        </group>
        <group
          position={[10.81, 129.001, -501.358]}
          rotation={[2.834, 1.025, -2.786]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_414__0.geometry}
            material={materials.Arch27_371__0}
            position={[3.806, 21.805, 54.607]}
          />
        </group>
        <group
          position={[-76.56, 245.232, -532.356]}
          rotation={[0.006, -0.001, -1.753]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_415__0.geometry}
            material={materials.Arch27_371__0}
            position={[7.957, 0, -8.758]}
          />
        </group>
        <group
          position={[-97.452, 182.724, -532.803]}
          rotation={[-1.586, 0.174, -3.113]}
          scale={[1.083, 1.465, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_416__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.039]}
          />
        </group>
        <group
          position={[-75.456, 245.348, -580.624]}
          rotation={[-1.571, -1.389, -3.139]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_417__0.geometry}
            material={materials.Arch27_371__0}
            position={[3.351, -0.466, -14.841]}
          />
        </group>
        <group
          position={[-85.523, 225.715, -477.119]}
          rotation={[-1.335, 0.177, 3.099]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_418__0.geometry}
            material={materials.Arch27_371__0}
            position={[4.035, 65.372, 67.337]}
          />
        </group>
        <group
          position={[-53.485, 309.815, -533.108]}
          rotation={[-1.638, 0.281, 2.84]}
          scale={[1.083, 1.465, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_419__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.039]}
          />
        </group>
        <group
          position={[-61.468, 289.599, -496.303]}
          rotation={[-1.525, 0.182, 3.133]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_420__0.geometry}
            material={materials.Arch27_371__0}
            position={[3.032, 18.608, 13.803]}
          />
        </group>
        <group
          position={[263.415, -214.558, -290.509]}
          rotation={[-0.006, 0.001, 1.389]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_421__0.geometry}
            material={materials.Arch27_371__0}
            position={[7.957, 0, -8.758]}
          />
        </group>
        <group
          position={[284.307, -152.05, -290.957]}
          rotation={[1.586, -0.174, 0.028]}
          scale={[1.083, 1.465, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_422__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.039]}
          />
        </group>
        <group
          position={[263.426, -214.499, -279.954]}
          rotation={[-0.006, 0.001, 1.389]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_423__0.geometry}
            material={materials.Arch27_371__0}
            position={[7.957, 0, -18.504]}
          />
        </group>
        <group
          position={[262.311, -214.673, -338.778]}
          rotation={[Math.PI / 2, 1.389, 0.003]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_424__0.geometry}
            material={materials.Arch27_371__0}
            position={[3.351, -0.466, -14.841]}
          />
        </group>
        <group
          position={[248.323, -258.925, -254.456]}
          rotation={[1.525, -0.182, -0.008]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_425__0.geometry}
            material={materials.Arch27_371__0}
            position={[3.032, 18.608, 13.803]}
          />
        </group>
        <group
          position={[272.378, -195.04, -235.273]}
          rotation={[1.335, -0.177, -0.042]}
          scale={1.083}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_426__0.geometry}
            material={materials.Arch27_371__0}
            position={[4.035, 65.372, 67.337]}
          />
        </group>
        <group
          position={[240.34, -279.14, -291.261]}
          rotation={[1.638, -0.281, -0.301]}
          scale={[1.083, 1.465, 1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arch27_427__0.geometry}
            material={materials.Arch27_371__0}
            position={[0, 0, -2.039]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/gym2.glb')
export default Machine